version: '3.7'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: kosicdb
    ports:
      - 5432:5432
    volumes:
      - ./provision/sql:/docker-entrypoint-initdb.d/
      - kosic-data:/var/lib/postgresql/data

volumes:
  kosic-data:


