name: local

spring:
  profiles: local
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/kosic"
    username: rackdon
    password: rackdon
    jpa:
      show-sql: true
      generate-ddl: false
  data:
    mongodb:
      authentication-database: admin
      database: kosic_test
      host: localhost
      port: 27017
      username: rackdon
      password: rackdon

server:
  port: 8080

logging:
  level:
    root: info
