management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always

info:
  app:
    name: 'Kosic service'
    description: 'Spring boot example'

logging:
  level:
    root: warn
  exception-conversion-word: "%replace(%xException){'\\n','\u2028'}%nopex"

springdoc:
  api-docs:
    path: /api-docs
