spring:
  profiles: mongo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  data:
    mongodb:
      authentication-database: ${MONGO_AUTHENTICATION_DB:admin}
      database: ${MONGO_DB:kosic}
      host: ${MONGO_DB_HOST:}
      port: ${MONGO_DB_PORT:}
      username: ${MONGO_DB_USERNAME:}
      password: ${MONGO_DB_PASSWORD}

logging:
  level:
    root: warn
  exception-conversion-word: "%replace(%xException){'\\n','\u2028'}%nopex"
