spring:
  profiles: local-jpa
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/kosic"
    username: rackdon
    password: rackdon
    jpa:
      show-sql: true
      generate-ddl: false

server:
  port: 8080

logging:
  level:
    root: info
