name: test

spring:
  profiles:
    active: test
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/kosic_test"
    username: rackdon
    password: rackdon
    jpa:
      show-sql: true
      generate-ddl: false
  data:
    mongodb:
      authentication-database: admin
      database: kosic_test
      host: localhost
      port: 27017
      username: rackdon
      password: rackdon

server:
  port: 8080

logging:
  level:
    root: info

info:
  app:
    name: 'Kosic service'
    description: 'Spring boot example'
